from pathlib import Path
p=Path('NullSignalMVP/app/build.gradle');x=p.read_text().replace('versionCode 20','versionCode 21').replace("versionName '2.0.0'","versionName '2.1.0'");p.write_text(x)
p=Path('NullSignalMVP/app/src/main/java/com/nullsignal/local/MainActivity.java');x=p.read_text()
x=x.replace('Negative-event intelligence + personal mobility memory.','Negative-event intelligence + commute-aware personal mobility memory.').replace('MOBILITY ENGINE · 2.0.0','COMMUTE + MOBILITY ENGINE · 2.1.0')
x=x.replace('Max-detail GPS (5-second target while service runs)','Max-detail GPS (5-second target during active commute tracking)').replace('Walking, running, cycling, vehicle and still states','Walking, running, cycling, motorized public-transit movement and still states').replace('nearby devices such as earbuds, watches and car systems.','nearby devices such as earbuds, watches and other personal accessories.')
a=x.find('        String parkLat=db.getState("parking_lat"');b=x.find('        long dayStart=',a)
commute='''        section("COMMUTE NOW");LinearLayout commute=card();long jid=parseLong(db.getState("mob_current_journey","0"));MobilityStore.JourneyRow aj=jid>0?ms.getJourney(jid):null;if(aj==null){commute.addView(text("No active journey",16,TEXT,true));commute.addView(text("Travel normally with live mobility enabled. NullSignal learns walking + public-transit commutes, duration, destination and route corridors.",13,MUTED,false));}else{MobilityStore.PlaceRow from=ms.getPlace(aj.startPlaceId),dest=ms.getPlace(aj.predictedDestPlaceId);long elapsed=System.currentTimeMillis()-aj.startTs;commute.addView(text((from==null?"Journey":from.display())+" → "+(dest==null?"destination learning":dest.display()),16,CYAN,true));commute.addView(text("Elapsed "+formatDuration(elapsed)+" · "+formatDistance(aj.distanceM)+" · "+friendlyMode(aj.mode)+" · "+aj.transfers+" transfer"+(aj.transfers==1?"":"s"),13,TEXT,false));if(dest!=null){MobilityStore.TransitionRow tr=ms.transition(aj.startPlaceId,aj.predictedDestPlaceId,ContextEngine.dayType(aj.startTs),ContextEngine.dayPart(aj.startTs));if(tr!=null&&tr.count>=3){long avg=(long)tr.meanDuration(),remaining=Math.max(0,avg-elapsed);commute.addView(text("Personal ETA: ~"+humanTs(System.currentTimeMillis()+remaining)+" · from "+tr.count+" comparable trips",13,CYAN,true));commute.addView(text("Typical total: "+formatDuration(avg)+" · variation ±"+formatDuration((long)tr.sdDuration()),12,MUTED,false));}}}long target=parseLong(db.getState("approach_target_place","0"));if(target>0){MobilityStore.PlaceRow tp=ms.getPlace(target);commute.addView(text("Arrival alarm: "+(tp==null?"Place "+target:tp.display())+" · ~800 m",13,AMBER,true));commute.addView(actionButton("Cancel arrival alarm",v->{db.putState("approach_target_place","0");render();}));}String exla=db.getState("last_transit_exit_lat",""),exlo=db.getState("last_transit_exit_lon","");long exts=parseLong(db.getState("last_transit_exit_ts","0"));if(!exla.isEmpty()&&!exlo.isEmpty()){commute.addView(text("Last transit exit: "+humanTs(exts),12,MUTED,false));commute.addView(actionButton("Open last transit exit in Maps",v->openMap(parseDouble(exla),parseDouble(exlo),"Last transit exit")));}long tw=parseLong(db.getState("last_transfer_wait_ms","0"));if(tw>0)commute.addView(text("Last transfer wait: "+formatDuration(tw),12,MUTED,false));root.addView(commute);spacer(14);\n\n'''
if a>=0 and b>a:x=x[:a]+commute+x[b:]
p.write_text(x)
