from pathlib import Path
p=Path("NullSignalMVP/app/src/main/java/com/nullsignal/local/MobilityStore.java");s=p.read_text()
s=s.replace('private static final int DB_VERSION=1;','private static final int DB_VERSION=2;')
s=s.replace('route_alerted INTEGER NOT NULL DEFAULT 0)','route_alerted INTEGER NOT NULL DEFAULT 0,transfers INTEGER NOT NULL DEFAULT 0)')
s=s.replace('@Override public void onUpgrade(SQLiteDatabase db,int oldVersion,int newVersion){}','@Override public void onUpgrade(SQLiteDatabase db,int oldVersion,int newVersion){if(oldVersion<2){try{db.execSQL("ALTER TABLE journeys ADD COLUMN transfers INTEGER NOT NULL DEFAULT 0");}catch(Exception ignored){}}}')
s=s.replace('predicted_dest_place_id,slow_alerted,route_alerted FROM journeys','predicted_dest_place_id,slow_alerted,route_alerted,transfers FROM journeys')
s=s.replace('new JourneyRow(c.getLong(0),c.getLong(1),c.getLong(2),c.getLong(3),c.getLong(4),c.getDouble(5),c.getLong(6),c.getString(7),c.getString(8),c.getLong(9),c.getInt(10)==1,c.getInt(11)==1)','new JourneyRow(c.getLong(0),c.getLong(1),c.getLong(2),c.getLong(3),c.getLong(4),c.getDouble(5),c.getLong(6),c.getString(7),c.getString(8),c.getLong(9),c.getInt(10)==1,c.getInt(11)==1,c.getInt(12))')
s=s.replace('public static class JourneyRow{public final long id,startTs,endTs,startPlaceId,endPlaceId,durationMs,predictedDestPlaceId;public final double distanceM;public final String mode,status;public final boolean slowAlerted,routeAlerted;JourneyRow(long id,long startTs,long endTs,long startPlaceId,long endPlaceId,double distanceM,long durationMs,String mode,String status,long predictedDestPlaceId,boolean slowAlerted,boolean routeAlerted){this.id=id;this.startTs=startTs;this.endTs=endTs;this.startPlaceId=startPlaceId;this.endPlaceId=endPlaceId;this.distanceM=distanceM;this.durationMs=durationMs;this.mode=mode;this.status=status;this.predictedDestPlaceId=predictedDestPlaceId;this.slowAlerted=slowAlerted;this.routeAlerted=routeAlerted;}}','public static class JourneyRow{public final long id,startTs,endTs,startPlaceId,endPlaceId,durationMs,predictedDestPlaceId;public final double distanceM;public final String mode,status;public final boolean slowAlerted,routeAlerted;public final int transfers;JourneyRow(long id,long startTs,long endTs,long startPlaceId,long endPlaceId,double distanceM,long durationMs,String mode,String status,long predictedDestPlaceId,boolean slowAlerted,boolean routeAlerted,int transfers){this.id=id;this.startTs=startTs;this.endTs=endTs;this.startPlaceId=startPlaceId;this.endPlaceId=endPlaceId;this.distanceM=distanceM;this.durationMs=durationMs;this.mode=mode;this.status=status;this.predictedDestPlaceId=predictedDestPlaceId;this.slowAlerted=slowAlerted;this.routeAlerted=routeAlerted;this.transfers=transfers;}}')
s=s.replace('public void updateJourneyDistance(long id,double distance,String mode){ContentValues v=new ContentValues();v.put("distance_m",distance);if(mode!=null)v.put("mode",mode);getWritableDatabase().update("journeys",v,"id=?",new String[]{String.valueOf(id)});}','public void updateJourneyDistance(long id,double distance,String mode){JourneyRow o=getJourney(id);ContentValues v=new ContentValues();v.put("distance_m",distance);if(mode!=null){String old=o==null?null:o.mode;String m=(old==null||old.isEmpty()||"unknown".equals(old)||old.equals(mode))?mode:("unknown".equals(mode)?old:"mixed commute");v.put("mode",m);}getWritableDatabase().update("journeys",v,"id=?",new String[]{String.valueOf(id)});}')
needle='    public void markSlowAlerted(long id)'
add='    public void incrementJourneyTransfers(long id){JourneyRow j=getJourney(id);if(j==null)return;ContentValues v=new ContentValues();v.put("transfers",j.transfers+1);getWritableDatabase().update("journeys",v,"id=?",new String[]{String.valueOf(id)});}\n    public List<TransitionRow> topTransitions(int limit){List<TransitionRow> out=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT start_place_id,end_place_id,day_type,part,count,duration_sum,duration_sq,distance_sum FROM transition_stats ORDER BY count DESC LIMIT "+Math.max(1,limit),null)){while(c.moveToNext())out.add(readTransition(c));}return out;}\n'
s=s.replace(needle,add+needle);p.write_text(s)
