from pathlib import Path
p=Path('NullSignalMVP/app/src/main/java/com/nullsignal/local/MainActivity.java');x=p.read_text()
freq='''        section("FREQUENT COMMUTES");List<MobilityStore.TransitionRow> trs=ms.topTransitions(8);if(trs.isEmpty()){LinearLayout e=card();e.addView(text("No repeated commute pairs learned yet",15,TEXT,true));e.addView(text("After several trips between the same places, personal average travel time becomes your ETA and delay baseline.",13,MUTED,false));root.addView(e);}else for(MobilityStore.TransitionRow tr:trs)root.addView(commutePatternCard(tr));spacer(14);\n\n'''
x=x.replace('        section("RECENT JOURNEYS");',freq+'        section("RECENT JOURNEYS");')
old='row.addView(map,lp);c.addView(row);margin(c);return c;}'
new='row.addView(map,lp);c.addView(row);c.addView(actionButton("Wake / alert me ~800 m before this place",v->{NullSignalDb.get(this).putState("approach_target_place",String.valueOf(p.id));NullSignalDb.get(this).putState("approach_radius_m","800");NullSignalDb.get(this).putState("approach_closest_m","");NullSignalDb.get(this).putState("approach_overshoot_alerted","0");toast("Arrival alarm armed for "+p.display());render();}));margin(c);return c;}'
x=x.replace(old,new,1)
x=x.replace('formatDistance(j.distanceM)+" · "+formatDuration(dur)+" · "+j.mode+" · "+j.status','formatDistance(j.distanceM)+" · "+formatDuration(dur)+" · "+friendlyMode(j.mode)+" · "+j.transfers+" transfer"+(j.transfers==1?"":"s")+" · "+j.status')
helper='''    private View commutePatternCard(MobilityStore.TransitionRow tr){MobilityStore ms=MobilityStore.get(this);MobilityStore.PlaceRow a=ms.getPlace(tr.startPlaceId),b=ms.getPlace(tr.endPlaceId);LinearLayout c=card();c.addView(text((a==null?"Place "+tr.startPlaceId:a.display())+" → "+(b==null?"Place "+tr.endPlaceId:b.display()),15,TEXT,true));c.addView(text(tr.count+" trips · average "+formatDuration((long)tr.meanDuration())+" · variation ±"+formatDuration((long)tr.sdDuration()),12,CYAN,false));c.addView(text(tr.dayType+" · "+tr.part,11,MUTED,false));margin(c);return c;}\n    private String friendlyMode(String m){if(m==null||m.isEmpty())return "unknown";if("mixed commute".equals(m))return "walking + public transit";return m;}\n'''
x=x.replace('    private View expectationCard(',helper+'    private View expectationCard(')
x=x.replace('NullSignal 2.0 keeps exact latitude/longitude, route points, speed, bearing and learned place visits so it can reconstruct journeys, find last-seen devices and learn mobility anomalies.','NullSignal 2.1 keeps exact GPS, route points, speed, bearing, public-transit segment transitions and learned places so it can reconstruct commutes, estimate personal ETA, detect route/delay anomalies and find last-seen devices.')
p.write_text(x)
